/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  2442: {
    TestEvaluation: {
      address: "0x9AA3ecB3449C527bA52b14253CD49D350356f529",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "testSetNumber",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "questionId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "chosenOptionIndex",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct TestEvaluation.UserResponse[]",
              name: "responses",
              type: "tuple[]",
            },
          ],
          name: "ResponseSubmitted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string[]",
              name: "options",
              type: "string[]",
            },
            {
              internalType: "uint256",
              name: "rightOptionIndex",
              type: "uint256",
            },
          ],
          name: "addQuestion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "currentTestSet",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "testSetNumber",
              type: "uint256",
            },
          ],
          name: "getUserResponses",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "questionId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "chosenOptionIndex",
                  type: "uint256",
                },
              ],
              internalType: "struct TestEvaluation.UserResponse[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "questions",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rightOptionIndex",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "testSetNumber",
              type: "uint256",
            },
          ],
          name: "startTest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "questionId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "chosenOptionIndex",
                  type: "uint256",
                },
              ],
              internalType: "struct TestEvaluation.UserResponse[]",
              name: "responses",
              type: "tuple[]",
            },
          ],
          name: "submitResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "testSets",
          outputs: [
            {
              internalType: "uint256",
              name: "setNumber",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
  31337: {
    TestEvaluation: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "testSetNumber",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "uint256",
                  name: "questionId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "chosenOptionIndex",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct TestEvaluation.UserResponse[]",
              name: "responses",
              type: "tuple[]",
            },
          ],
          name: "ResponseSubmitted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string[]",
              name: "options",
              type: "string[]",
            },
            {
              internalType: "uint256",
              name: "rightOptionIndex",
              type: "uint256",
            },
          ],
          name: "addQuestion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "currentTestSet",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "testSetNumber",
              type: "uint256",
            },
          ],
          name: "getUserResponses",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "questionId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "chosenOptionIndex",
                  type: "uint256",
                },
              ],
              internalType: "struct TestEvaluation.UserResponse[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "questions",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "rightOptionIndex",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "testSetNumber",
              type: "uint256",
            },
          ],
          name: "startTest",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "questionId",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "chosenOptionIndex",
                  type: "uint256",
                },
              ],
              internalType: "struct TestEvaluation.UserResponse[]",
              name: "responses",
              type: "tuple[]",
            },
          ],
          name: "submitResponse",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "testSets",
          outputs: [
            {
              internalType: "uint256",
              name: "setNumber",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
